/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "ming's blog",
  "description": "好好学习，天天向上",
  "base": "/",
  "headTags": [
    [
      "link",
      {
        "rel": "icon",
        "href": "/favicon.ico"
      }
    ],
    [
      "meta",
      {
        "name": "viewport",
        "content": "width=device-width,initial-scale=1,user-scalable=no"
      }
    ]
  ],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroText": "好好学习，天天向上",
        "tagline": null,
        "heroImageStyle": {
          "maxWidth": "600px",
          "width": "100%",
          "display": "block",
          "margin": "9rem auto 2rem",
          "background": "#fff",
          "borderRadius": "1rem"
        },
        "bgImage": "/home-bg.jpg",
        "bgImageStyle": {
          "height": "95vh"
        },
        "isShowTitleInHome": false,
        "actionText": "Guide",
        "actionLink": "/views/other/guide",
        "features": [
          {
            "title": "Yesterday",
            "details": "开发一款看着开心、写着顺手的 vuepress 博客主题"
          },
          {
            "title": "Today",
            "details": "希望帮助更多的人花更多的时间在内容创作上，而不是博客搭建上"
          },
          {
            "title": "Tomorrow",
            "details": "希望更多的爱好者能够参与进来，帮助这个主题更好的成长"
          }
        ]
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-15b99ca4",
      "path": "/"
    },
    {
      "title": "first page in category1",
      "frontmatter": {
        "title": "first page in category1",
        "date": "2018-12-15T00:00:00.000Z",
        "tags": [
          "tag1"
        ],
        "categories": [
          "category1"
        ]
      },
      "regularPath": "/blogs/category1/2018/121501.html",
      "relativePath": "blogs/category1/2018/121501.md",
      "key": "v-45dca2ca",
      "path": "/blogs/category1/2018/121501.html"
    },
    {
      "title": "second page in category1",
      "frontmatter": {
        "title": "second page in category1",
        "date": "2019-09-21T00:00:00.000Z",
        "tags": [
          "tag2"
        ],
        "categories": [
          "category1"
        ]
      },
      "regularPath": "/blogs/category1/2019/092101.html",
      "relativePath": "blogs/category1/2019/092101.md",
      "key": "v-093f3f0a",
      "path": "/blogs/category1/2019/092101.html",
      "excerpt": "<p>这里的内容会被显示成摘要。</p>\n<ol>\n<li>可以放置文案；</li>\n<li>可以放置图片作为文章封面。</li>\n</ol>\n"
    },
    {
      "title": "first page in category2",
      "frontmatter": {
        "title": "first page in category2",
        "date": "2016-12-15T00:00:00.000Z",
        "tags": [
          "tag3"
        ],
        "categories": [
          "category2"
        ]
      },
      "regularPath": "/blogs/category2/2016/121501.html",
      "relativePath": "blogs/category2/2016/121501.md",
      "key": "v-b1cd81ac",
      "path": "/blogs/category2/2016/121501.html"
    },
    {
      "title": "一个前端。目前就职于宁波某互联网公司。",
      "frontmatter": {
        "layout": "About",
        "hiddenInHome": true
      },
      "regularPath": "/about/",
      "relativePath": "about/README.md",
      "key": "v-34e0ef55",
      "path": "/about/",
      "headers": [
        {
          "level": 3,
          "title": "一个前端。目前就职于宁波某互联网公司。",
          "slug": "一个前端。目前就职于宁波某互联网公司。"
        },
        {
          "level": 3,
          "title": "博客技术栈:",
          "slug": "博客技术栈"
        }
      ]
    },
    {
      "title": "second page in category2",
      "frontmatter": {
        "title": "second page in category2",
        "date": "2017-09-21T00:00:00.000Z",
        "tags": [
          "tag4"
        ],
        "categories": [
          "category2"
        ]
      },
      "regularPath": "/blogs/category2/2017/092101.html",
      "relativePath": "blogs/category2/2017/092101.md",
      "key": "v-6a7bdb6a",
      "path": "/blogs/category2/2017/092101.html"
    },
    {
      "title": "vuepress-theme-reco",
      "frontmatter": {
        "title": "vuepress-theme-reco",
        "date": "2019-04-09T00:00:00.000Z"
      },
      "regularPath": "/blogs/other/guide.html",
      "relativePath": "blogs/other/guide.md",
      "key": "v-2374da86",
      "path": "/blogs/other/guide.html",
      "headers": [
        {
          "level": 2,
          "title": "Use",
          "slug": "use"
        },
        {
          "level": 2,
          "title": "Play Together",
          "slug": "play-together"
        },
        {
          "level": 3,
          "title": "0.x",
          "slug": "_0-x"
        },
        {
          "level": 3,
          "title": "1.x",
          "slug": "_1-x"
        },
        {
          "level": 3,
          "title": "CLI",
          "slug": "cli"
        },
        {
          "level": 2,
          "title": "License",
          "slug": "license"
        }
      ]
    },
    {
      "title": "theme-reco",
      "frontmatter": {
        "title": "theme-reco",
        "date": "2020-05-29T00:00:00.000Z"
      },
      "regularPath": "/docs/theme-reco/",
      "relativePath": "docs/theme-reco/README.md",
      "key": "v-37f35198",
      "path": "/docs/theme-reco/"
    },
    {
      "title": "api",
      "frontmatter": {
        "title": "api",
        "date": "2020-05-29T00:00:00.000Z"
      },
      "regularPath": "/docs/theme-reco/api.html",
      "relativePath": "docs/theme-reco/api.md",
      "key": "v-4bc3e1d7",
      "path": "/docs/theme-reco/api.html"
    },
    {
      "title": "plugin",
      "frontmatter": {
        "title": "plugin",
        "date": "2020-05-28T00:00:00.000Z"
      },
      "regularPath": "/docs/theme-reco/plugin.html",
      "relativePath": "docs/theme-reco/plugin.md",
      "key": "v-744727ad",
      "path": "/docs/theme-reco/plugin.html"
    },
    {
      "title": "theme",
      "frontmatter": {
        "title": "theme",
        "date": "2020-05-27T00:00:00.000Z"
      },
      "regularPath": "/docs/theme-reco/theme.html",
      "relativePath": "docs/theme-reco/theme.md",
      "key": "v-198d4412",
      "path": "/docs/theme-reco/theme.html"
    },
    {
      "frontmatter": {
        "layout": "Tags",
        "title": "Tags"
      },
      "regularPath": "/tag/",
      "key": "v-b1564aac",
      "path": "/tag/"
    },
    {
      "frontmatter": {
        "layout": "FrontmatterKey",
        "title": "Categories"
      },
      "regularPath": "/categories/",
      "key": "v-ef9325c4",
      "path": "/categories/"
    },
    {
      "frontmatter": {
        "layout": "TimeLines",
        "title": "Timeline"
      },
      "regularPath": "/timeline/",
      "key": "v-6319eb4e",
      "path": "/timeline/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "tag1 Tags"
      },
      "regularPath": "/tag/tag1/",
      "key": "v-1368f264",
      "path": "/tag/tag1/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "tag2 Tags"
      },
      "regularPath": "/tag/tag2/",
      "key": "v-1368f226",
      "path": "/tag/tag2/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "tag3 Tags"
      },
      "regularPath": "/tag/tag3/",
      "key": "v-1368f1e8",
      "path": "/tag/tag3/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "tag4 Tags"
      },
      "regularPath": "/tag/tag4/",
      "key": "v-1368f1aa",
      "path": "/tag/tag4/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "category1 Categories"
      },
      "regularPath": "/categories/category1/",
      "key": "v-5ce69b3a",
      "path": "/categories/category1/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "category2 Categories"
      },
      "regularPath": "/categories/category2/",
      "key": "v-5ce69b59",
      "path": "/categories/category2/"
    }
  ],
  "themeConfig": {
    "locales": {
      "/": {
        "recoLocales": {
          "homeBlog": {
            "article": "文章",
            "tag": "标签",
            "category": "分类",
            "friendLink": "友情链接"
          },
          "pagation": {
            "prev": "上一页",
            "next": "下一页",
            "go": "前往",
            "jump": "跳转至"
          }
        }
      }
    },
    "nav": [
      {
        "text": "主页",
        "link": "/",
        "icon": "reco-home"
      },
      {
        "text": "时间轴",
        "link": "/timeline/",
        "icon": "reco-date"
      },
      {
        "text": "文档",
        "icon": "reco-message",
        "items": [
          {
            "text": "vuepress-reco",
            "link": "/docs/theme-reco/"
          }
        ]
      },
      {
        "text": "联系",
        "icon": "reco-message",
        "items": [
          {
            "text": "GitHub",
            "link": "https://github.com/recoluan",
            "icon": "reco-github"
          }
        ]
      },
      {
        "text": "关于",
        "link": "/about/",
        "icon": "reco-account"
      }
    ],
    "sidebar": {
      "/docs/theme-reco/": [
        "",
        "theme",
        "plugin",
        "api"
      ]
    },
    "type": "blog",
    "blogConfig": {
      "category": {
        "location": 2,
        "text": "分类"
      },
      "tag": {
        "location": 3,
        "text": "标签"
      }
    },
    "friendLink": [
      {
        "title": "午后南杂",
        "desc": "Enjoy when you can, and endure when you must.",
        "email": "1156743527@qq.com",
        "link": "https://www.recoluan.com"
      },
      {
        "title": "vuepress-theme-reco",
        "desc": "A simple and beautiful vuepress Blog & Doc theme.",
        "avatar": "https://vuepress-theme-reco.recoluan.com/icon_vuepress_reco.png",
        "link": "https://vuepress-theme-reco.recoluan.com"
      }
    ],
    "logo": "/logo.png",
    "search": true,
    "searchMaxSuggestions": 10,
    "lastUpdated": "最后更新时间",
    "author": "gnimiah",
    "authorAvatar": "/avatar.png",
    "record": "gnimiah",
    "startYear": "2017"
  },
  "locales": {
    "/": {
      "lang": "zh-CN",
      "path": "/"
    }
  }
}